MxOnline/MxOnline/urls.py
# from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
# from django.conf.urls.static import static
from MxOnline.settings import MEDIA_ROOT,STATICFILES_DIRS

import xadmin
from MxOnline import views

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('index/', views.index, name = 'index'),
    path('login/', views.mx_login, name = 'login'),
    path('logout/', views.mx_logout, name = 'logout'),
    path('register/', views.register, name = 'register'),
    # re_path('active/(?P<active_code>.*)/',ActiveUserView.as_view(),name='user_active'),
    re_path(r'^active/(\w+)/',views.user_active,name='user_active'),# 邮箱激活账号
    path('forgetpwd/',views.forget_pwd,name='forgetpwd'), # 忘记密码
    re_path(r'^reset/(\w+)/',views.pwd_reset,name='reset'), # 邮箱重置密码链接
    path('modify_pwd/',views.modify_pwd,name='modify_pwd'), # 重置密码

    # 验证码
    re_path(r'^captcha', include('captcha.urls')),

    # 所有organization相关的url链接，都转到organization包中的urls.py处理
    path('org/',include("organization.urls")),
    #course下的url跳转
    path("course/", include('course.urls')),
    #个人信息
    path("users/", include('users.urls')),

    # 处理静态文件,使用Django自带serve,传入setting中路径配置MEDIAROOT，让它根据路径找media下的文件
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT }),

    #当setting中DEBUG设置为False时，django不会再自动帮你处理setting中设置好的static_dirs路径，
    #需要手动static_dirs路径，然后使用serve根据路径帮忙找到static下的文件
    # re_path(r'^static/(?P<path>.*)', serve, {"document_root": STATICFILES_DIRS[0] }),

    # 富文本相关url
    path('ueditor/',include('DjangoUeditor.urls' )),

]
# urlpatterns += static('/media/', document_root=MEDIA_ROOT)

# 全局404页面配置
# handler404 = 'users.views.pag_not_found'
# 全局500页面配置
# handler500 = 'MxOnline.views.page_error'

MxOnline/extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

MxOnline/apps/course/models.py
from django.db import models
from datetime import datetime
from organization.models import CourseOrg,Teacher
from extra_apps.DjangoUeditor.models import UEditorField

# Create your models here.

class Course(models.Model):
    '''课程'''
    DEGREE_CHOICES = (
        ("cj", "初级"),
        ("zj", "中级"),
        ("gj", "高级"),
    )
    name = models.CharField("课程名",max_length=50)
    desc = models.CharField("课程描述",max_length=300)
    # detail = models.TextField("课程详情")
    detail = UEditorField(verbose_name='课程详情', width=600, height=300, imagePath="courses/ueditor/",
                          filePath="courses/ueditor/", default='')


    degree = models.CharField('难度',choices=DEGREE_CHOICES, max_length=2)
    learn_times = models.IntegerField("学习时长(分钟数)",default=0)
    students = models.IntegerField("学习人数",default=0)
    fav_nums = models.IntegerField("收藏人数",default=0)
    image = models.ImageField("封面图",upload_to="courses/%Y/%m",max_length=100)
    click_nums = models.IntegerField("点击数",default=0)
    tag = models.CharField('课程标签',default='',max_length=10)
    is_banner = models.BooleanField('是否轮播',default=False)
    is_public = models.BooleanField('是否是公开课',default=False)
    add_time = models.DateTimeField("添加时间",default=datetime.now,)
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name="所属机构", null=True, blank=True)
    category = models.CharField("课程类别",max_length=20, default="")
    teacher = models.ForeignKey(Teacher,verbose_name='讲师',null=True,blank=True,on_delete=models.CASCADE)
    youneed_know = models.CharField('课程须知',max_length=300,default='')
    teacher_tell = models.CharField('老师告诉你',max_length=300,default='')

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        #获取课程的章节数
        return self.lesson_set.all().count()
    get_zj_nums.short_description = '章节数'   #在后台显示的名称

    def go_to(self):
        from django.utils.safestring import mark_safe
        #mark_safe后就不会转义
        return mark_safe("<a href='https://home.cnblogs.com/u/derek1184405959/'>跳转</a>")
    go_to.short_description = "跳转"

    def get_course_lesson(self):
        #获取课程所有章节
        return self.lesson_set.all()

    def get_learn_users(self):
        #获取这门课程的学习用户
        return self.usercourse_set.all()[:5]


    def __str__(self):
        return self.name


class Lesson(models.Model):
    '''课程章节'''
    course = models.ForeignKey(Course,verbose_name='课程',on_delete=models.CASCADE)
    name = models.CharField("章节名",max_length=100)
    add_time = models.DateTimeField("添加时间",default=datetime.now)

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name
        unique_together = ('course','name')

    def get_lesson_vedio(self):
        #获取章节所有视频
        return self.video_set.all()


    def __str__(self):
        return "%s%s"% (self.course,self.name)


class Video(models.Model):
    '''章节视频'''
    lesson = models.ForeignKey(Lesson, verbose_name="章节",on_delete=models.CASCADE)
    name = models.CharField("视频名",max_length=100)
    url = models.CharField('访问地址',default='',max_length=200)
    learn_times = models.IntegerField("学习时长(分钟数)", default=0)
    add_time = models.DateTimeField("添加时间", default=datetime.now)

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """课程资源"""
    course = models.ForeignKey(Course, verbose_name="课程",on_delete=models.CASCADE)
    name = models.CharField("名称",max_length=100)
    download = models.FileField("资源文件",upload_to="course/resource/%Y/%m",max_length=100)
    add_time = models.DateTimeField("添加时间", default=datetime.now)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

MxOnline/MxOnline/forms.py
from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    '''登录验证表单'''
    username = forms.CharField(required=True)
    password = forms.CharField(required=True,min_length=5)


class RegisterForm(forms.Form):
    '''注册验证表单'''
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=5)
    # 验证码
    captcha = CaptchaField(error_messages={'invalid':'验证码错误'})


class ForgetPwdForm(forms.Form):
    '''忘记密码'''
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': '验证码错误'})


class ModifyPwdForm(forms.Form):
    '''重置密码'''
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)

MxOnline/apps/organization/views.py
from django.shortcuts import render,redirect,HttpResponse
from organization import models
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from organization import forms
from course.models import Course
from operation.models import UserFavorite
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

# Create your views here.
def org_list(request):
    """课程机构列表"""
    # 所有课程机构
    all_orgs = models.CourseOrg.objects.all()
    # 所有城市
    all_citys = models.CityDict.objects.all()

    # 热门课程机构排名
    hot_orgs = all_orgs.order_by('-click_nums')[:4]

    # 机构搜索功能
    search_keywords = request.GET.get('keywords', '')
    if search_keywords:
        # 在name字段进行操作,做like语句的操作。i代表不区分大小写
        # or操作使用Q
        all_orgs = all_orgs.filter(Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords))

    # 城市筛选
    city_id = request.GET.get('city','')
    if city_id:
        all_orgs = all_orgs.filter(city_id = int(city_id))
    # 类别筛选
    category =request.GET.get('ct','')
    if category:
        all_orgs = all_orgs.filter(category=category)

    orgs_count = all_orgs.count() # 课程机构总数

    # 学习人数和课程数筛选
    sort = request.GET.get('sort', "")
    if sort:
        all_orgs = all_orgs.order_by('-' + sort)

    # 开始分页功能
    paginator = Paginator(all_orgs, 5)
    page = request.GET.get('_page',1)
    try:
        orgs = paginator.page(page) # 当前页显示的5个数据
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        orgs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        orgs = paginator.page(paginator.num_pages)  # paginator.num_pages：总页数，即返回最后一页

    return render(request,'organization/org-list.html',locals())


def add_user_ask(request):
    """用户咨询"""
    if request.method == 'POST':
        userask_form = forms.UserAskForm(request.POST)
        if userask_form.is_valid():
            user_ask = userask_form.save()
            # 如果保存成功,返回json字符串,后面content type是告诉浏览器返回的数据类型
            return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            # 如果保存失败，返回json字符串,并将form的报错信息通过msg传递到前端
            return HttpResponse('{"status":"fail", "msg":"添加出错"}', content_type='application/json')


def org_detail_home(request,org_id):
    """课程机构详情页"""

    current_page = 'home'
    # 根据id找到课程机构
    course_org = models.CourseOrg.objects.get(id=org_id)
    course_org.click_nums += 1
    course_org.save()
    # 判断收藏状态
    has_fav = False
    if request.user.is_authenticated:
        if UserFavorite.objects.filter(user=request.user, fav_id=course_org.id, fav_type=2):
            has_fav = True
    # 反向查询到课程机构的所有课程和老师

    courses = course_org.course_set.all()[:4]
    teachers = course_org.teacher_set.all()[:2]
    return render(request,'organization/org_detail_base.html',locals())

def org_course_home(request,course_org_id):
    """机构课程页"""
    current_page = 'course'

    course_org = models.CourseOrg.objects.get(id = course_org_id)
    # 通过课程机构的id找到对应课程
    all_courses = Course.objects.filter(course_org_id=course_org_id)
    # 判断收藏状态
    has_fav = False
    if request.user.is_authenticated:
        if UserFavorite.objects.filter(user=request.user, fav_id=course_org_id, fav_type=2):
            has_fav = True

    return render(request,'organization/org-detail-course.html',locals())


def org_detail_desc(request,course_org_id):
    """机构课程页"""
    current_page = 'desc'
    # 课程机构
    course_org = models.CourseOrg.objects.get(id = course_org_id)

    # 判断收藏状态
    has_fav = False
    if request.user.is_authenticated:
        if UserFavorite.objects.filter(user=request.user, fav_id=course_org_id, fav_type=2):
            has_fav = True

    return render(request,'organization/org-detail-desc.html',locals())


def org_detail_teacher(request,course_org_id):
    """机构课程页"""
    current_page = 'teacher'
    # 课程机构
    course_org = models.CourseOrg.objects.get(id = course_org_id)
    # 所有讲师
    teachers = course_org.teacher_set.all()

    # 判断收藏状态
    has_fav = False
    if request.user.is_authenticated:
        if UserFavorite.objects.filter(user=request.user, fav_id=course_org_id, fav_type=2):
            has_fav = True

    return render(request,'organization/org-detail-teachers.html',locals())


def user_fav(request):
    if request.method == 'POST':
        id = request.POST.get('fav_id', 0)  # 防止后边int(fav_id)时出错
        type = request.POST.get('fav_type', 0)  # 防止int(fav_type)出错

        if not request.user.is_authenticated:
            # 未登录时返回json提示未登录，跳转到登录页面是在ajax中做的
            return HttpResponse('{"status":"fail", "msg":"用户未登录"}', content_type='application/json')

        exist_record = UserFavorite.objects.filter(user=request.user, fav_id=int(id), fav_type=int(type))
        if exist_record:
            # 如果记录已经存在，表示用户取消收藏
            exist_record.delete()
            if int(type) == 1:
                course = Course.objects.get(id=int(id))
                course.fav_nums -= 1
                if course.fav_nums < 0:
                    course.fav_nums = 0
                course.save()
            elif int(type) == 2:
                org = models.CourseOrg.objects.get(id=int(id))
                org.fav_nums -= 1
                if org.fav_nums < 0:
                    org.fav_nums = 0
                org.save()
            elif int(type) == 3:
                teacher = models.Teacher.objects.get(id=int(id))
                teacher.fav_nums -= 1
                if teacher.fav_nums < 0:
                    teacher.fav_nums = 0
                teacher.save()
            return HttpResponse('{"status":"success", "msg":"点击收藏"}', content_type='application/json')
        else:
            user_fav = UserFavorite()
            if int(type) > 0 and int(id) > 0:
                user_fav.fav_id = int(id)
                user_fav.fav_type = int(type)
                user_fav.user = request.user
                user_fav.save()

                if int(type) == 1:
                    course = Course.objects.get(id=int(id))
                    course.fav_nums += 1
                    course.save()
                elif int(type) == 2:
                    org = models.CourseOrg.objects.get(id=int(id))
                    org.fav_nums += 1
                    org.save()
                elif int(type) == 3:
                    teacher = models.Teacher.objects.get(id=int(id))
                    teacher.fav_nums += 1
                    teacher.save()
                return HttpResponse('{"status":"success", "msg":"已收藏"}', content_type='application/json')
            else:
                return HttpResponse('{"status":"fail", "msg":"收藏出错"}', content_type='application/json')


# 讲师列表
class TeacherListView(View):
    def get(self, request):
        all_teachers = models.Teacher.objects.all().order_by('add_time')
        print(all_teachers)
        # 总共有多少老师使用count进行统计
        teacher_nums = all_teachers.count()

        # 搜索功能
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            # 在name字段进行操作,做like语句的操作。i代表不区分大小写
            # or操作使用Q
            all_teachers = all_teachers.filter(name__icontains=search_keywords)
        # 人气排序
        sort = request.GET.get('sort', '')
        if sort:
            if sort == 'hot':
                all_teachers = all_teachers.order_by('-click_nums')

        # 讲师排行榜
        sorted_teacher = models.Teacher.objects.all().order_by('-click_nums')[:3]
        # 进行分页
        paginator = Paginator(all_teachers, 3)
        page = request.GET.get('_page', 1)
        try:
            teachers = paginator.page(page)  # 当前页显示的3个数据
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            teachers = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            teachers = paginator.page(paginator.num_pages)  # paginator.num_pages：总页数，即返回最后一页
        return render(request, "teachers/teachers-list.html",locals())


#讲师详情
class TeacherDetailView(LoginRequiredMixin,View):
    def get(self,request,teacher_id):
        teacher = models.Teacher.objects.get(id=teacher_id)
        teacher.click_nums += 1
        teacher.save()
        all_course = Course.objects.filter(teacher=teacher)
        # 教师收藏和机构收藏
        has_teacher_faved = False
        if UserFavorite.objects.filter(user=request.user, fav_type=3, fav_id=teacher.id):
            has_teacher_faved = True

        has_org_faved = False
        if UserFavorite.objects.filter(user=request.user, fav_type=2, fav_id=teacher.org.id):
            has_org_faved = True
        # 讲师排行榜
        sorted_teacher = models.Teacher.objects.all().order_by('-click_nums')[:3]
        return render(request,'teachers/teacher-detail.html',locals())

MxOnline/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p style="color: red;">链接已经失效</p>
</body>
</html>

MxOnline/templates/active_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>mx教育邮箱注册成功</title>
</head>
<body>
<h3>恭喜！您已成功激活账号：{{ email_count }}</h3>
<p style="color: red">点击跳转：<a href="/login/">登录</a></p>
</body>
</html>

MxOnline/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>课程机构列表 - 慕学在线网</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
    
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->

                        
                        <!-- <a style="color:white" class="fr registerbtn" href="register.html">注册</a> -->
                        <!-- <a style="color:white" class="fr loginbtn" href="login.html">登录</a>  -->
					{% if request.user.is_authenticated%}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'user_info' %}">进入个人中心</a>
	                                <a class="fr" href="/logout/">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="/register/">注册</a>
                        <a style="color:white" class="fr loginbtn" href="/login/">登录</a>
                    {% endif %}


				</div>
			</div>
{#            header部分#}
            <div class="middle">
                <div class="wp">
                    <a href="/index/"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>
            
            
			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
{#							<li {% if request.path|slice:'6' == '/index' %}class="active"{% endif %} ><a href="{% url 'index' %}">首页</a></li>#}
							<li {% if request.path == '/index/' %}class="active"{% endif %} ><a href="{% url 'index' %}">首页</a></li>
							<li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %} >
								<a href="{% url 'course_list' %}">
									公开课<img class="hot" src="/static/images/nav_hot.png">
								</a>
							</li>
							<li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
								<a href="{% url 'teacher_list' %}">授课教师</a>
							</li>
							<li {% if request.path|slice:'9' == '/org/list' %}class="active"{% endif %} >
							    <a href="{% url 'org_list' %}">授课机构</a>
                            </li>
						</ul>
					</div>
				</div>
			</nav>
            
			</div>
    </header>
</section>
<!--crumbs start-->


<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    {% for banner in all_banners %}
                        <li>
                            <a href="{{ banner.url }}">
                                <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}"/>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
    </div>
</div>
<!--banner end-->
<!--feature start-->
<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="{% static 'images/feature1.png' %}"/>
                <p class="center">专业权威</p>
            </li>
            <li class="feature2">
                <img class="pic" src="{% static 'images/feature2.png' %}"/>
                <p class="center">课程最新</p>
            </li>
            <li class="feature3">
                <img class="pic" src="{% static 'images/feature3.png' %}"/>
                <p class="center">名师授课</p>
            </li>
            <li class="feature4">
                <img class="pic" src="{% static 'images/feature4.png' %}"/>
                <p class="center">数据真实</p>
            </li>
        </ul>
    </div>
</section>
<!--feature end-->
<!--module1 start-->
<section>
    <div class="module">
        <div class="wp">
            <h1>公开课程</h1>
            <div class="module1 eachmod">
                <div class="module1_1 left">
                    <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                    <p class="fisrt_word">名师授课<br/>专业权威</p>
                    <a class="more" href="{% url 'course_list' %}">查看更多课程 ></a>
                </div>
                <div class="right group_list">
                    <div class="module1_2 box">
                        <div class="imgslide2">
                            <ul class="imgs">
                                {% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course_detail' banner_course.id %}">
                                            <img width="470" height="300"
                                                 src="{{ MEDIA_URL }}{{ banner_course.image }}"/>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="unslider-arrow2 prev"></div>
                        <div class="unslider-arrow2 next"></div>
                    </div>
                    {% for course in courses %}
                        <div class="module1_{{ forloop.counter|add:2 }} box">
                            <a href="{% url 'course_detail' course.id %}">
                                <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course_detail' course.id %}">
                                    <h2 title="django入门">{{ course.name }}</h2>
                                </a>
                                <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                                <span class="star fr">{{ course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="module greybg">
        <div class="wp">
            <h1>课程机构</h1>
            <div class="module3 eachmod">
                <div class="module3_1 left">
                    <img width="228" height="463" src="/static/images/module3_1.jpg"/>
                    <p class="fisrt_word">名校来袭<br/>权威认证</p>
                    <a class="more" href="{% url 'org_list' %}">查看更多机构 ></a>
                </div>
                <div class="right">
                    <ul>
                        {% for org in course_orgs %}
                            <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                <a href="{% url 'org_detail_home' org.id %}">
                                    <div class="company">
                                        <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ org.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="/static/images/footlogo.png"/></a></li>
					<li class="code"><img src="/static/images/code.jpg"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="/static/images/tell.png"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
<script src="/static/js/deco-common.js"  type="text/javascript"></script>

    <script type="text/javascript" src="/static/js/index.js"></script>

</body>
</html>

MxOnline/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>密码修改</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_pwd' %}" method="post">
        {% csrf_token %}
            <ul>
                <li class="{% if modify_form.errors.password1.0 %} errorput {% endif %}">
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}">
                <li class="{% if modify_form.errors.password2.0 %} errorput {% endif %}">
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div class="error btns" id="jsPasswdResetTips" style="color: red">
                    {% for key,error in modify_form.errors.items %}{{ key }}:{{ error }}{% endfor %}{{ msg }}
                </div>
                <li class="button">
                    <input type="submit" value="提交">
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

MxOnline/templates/send_email_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>【密码重置】邮件已发送，请移步邮箱中查收！</p>
</body>
</html>